services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # SECURITY
    #

    # standard user provider returning admin users wrapped in a Pimcore\Bundle\AdminBundle\Security\User\User proxy object.
    # using this user provider allows implementations to authenticate against pimcore users on every desired firewall
    Pimcore\Bundle\AdminBundle\Security\User\UserProvider:
        public: true

    # the password hasher factory builds a dedicated hasher per user
    # as we need the user instance to hash passwords.
    # we don't specifiy this as fully qualified class name as there can be multiple factories (one for each user type)
    pimcore_admin.security.password_hasher_factory:
        class: Pimcore\Security\Hasher\Factory\UserAwarePasswordHasherFactory
        arguments:
            - Pimcore\Bundle\AdminBundle\Security\Hasher\AdminPasswordHasher

    # Authenticators for handling admin login and session authentications
    Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminTokenAuthenticator:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    Pimcore\Bundle\AdminBundle\Security\Event\LogoutListener:
        tags:
            - { name: 'kernel.event_subscriber', dispatcher: 'security.event_dispatcher.pimcore_admin'}

    Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver:
        public: true
        arguments:
            - '@security.token_storage'

    Pimcore\Bundle\AdminBundle\Security\User\UserLoader: ~

    Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler:
        public: true
        arguments:
            - '%pimcore_admin.csrf_protection.excluded_routes%'
            - '@twig'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: security }

    Pimcore\Bundle\AdminBundle\Security\ContentSecurityPolicyHandler:
        public: true
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    # user checker checking admin users for validity
    Pimcore\Bundle\AdminBundle\Security\User\UserChecker: ~

