services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\AdminBundle\Security\Event\LogoutListener:
        tags:
            - { name: 'kernel.event_subscriber', dispatcher: 'security.event_dispatcher.pimcore_admin'}