# Pimcore
pimcore_admin:
    session:
        attribute_bags:
            - pimcore_admin
            - pimcore_objects
            - pimcore_copy
            - pimcore_gridconfig
            - pimcore_importconfig

    translations:
        path: "@PimcoreCoreBundle/translations"

    user:
        default_key_bindings:
            save:
                key: 'S'
                action: save
                ctrl: true
            publish:
                key: 'P'
                action: publish
                ctrl: true
                shift: true
            unpublish:
                key: 'U'
                action: unpublish
                ctrl: true
                shift: true
            rename:
                key: 'R'
                action: rename
                alt: true
                shift: true
            refresh:
                key: 't'
                action: refresh
            open_asset:
                key: 'A'
                action: openAsset
                ctrl: true
                shift: true
            open_object:
                key: 'O'
                action: openObject
                ctrl: true
                shift: true
            open_document:
                key: 'D'
                action: openDocument
                ctrl: true
                shift: true
            open_class_editor:
                key: 'C'
                action: openClassEditor
                ctrl: true
                shift: true
            open_in_tree:
                key: 'L'
                action: openInTree
                ctrl: true
                shift: true
            show_meta_info:
                key: 'I'
                action: showMetaInfo
                alt: true
            search_document:
                key: 'W'
                action: searchDocument
                alt: true
            search_asset:
                key: 'A'
                action: searchAsset
                alt: true
            search_object:
                key: 'O'
                action: searchObject
                alt: true
            show_element_history:
                key: 'H'
                action: showElementHistory
                alt: true
            close_all_tabs:
                key: 'T'
                action: closeAllTabs
                alt: true
            search_and_replace_assignments:
                key: 'S'
                action: searchAndReplaceAssignments
                alt: true
            redirects:
                key: 'R'
                action: redirects
                ctrl: false
                alt: true
            shared_translations:
                key: 'T'
                action: sharedTranslations
                ctrl: true
                alt: true
            recycle_bin:
                key: 'R'
                action: recycleBin
                ctrl: true
                alt: true
            notes_events:
                key: 'N'
                action: notesEvents
                ctrl: true
                alt: true
            tag_manager:
                key: 'H'
                action: tagManager
                ctrl: true
                alt: true
            tag_configuration:
                key: 'N'
                action: tagConfiguration
                ctrl: true
                alt: true
            users:
                key: 'U'
                action: users
                ctrl: true
                alt: true
            roles:
                key: 'P'
                action: roles
                ctrl: true
                alt: true
            clear_all_caches:
                key: 'Q'
                action: clearAllCaches
                ctrl: false
                alt: true
            clear_data_cache:
                key: 'C'
                action: clearDataCache
                ctrl: false
                alt: true
    documents:
        email_search: ['email']
# adds support for admin related routes that will be used to determine the request context in PimcoreContextGuesser

    security_firewall:
        pattern: ^/admin(/.*)?$
        user_checker: Pimcore\Security\User\UserChecker
        provider: pimcore_admin
        login_throttling:
            max_attempts: 3
            interval: '5 minutes'
        logout:
            path: pimcore_admin_logout
            target: pimcore_admin_login
        form_login:
            default_target_path: pimcore_admin_index
            always_use_default_target_path: true
            login_path: pimcore_admin_login
            check_path: pimcore_admin_login_check
            username_parameter: username
            password_parameter: password
        custom_authenticators:
            - Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminTokenAuthenticator
        two_factor:
            auth_form_path: /admin/login/2fa                   # Path or route name of the two-factor form
            check_path: /admin/login/2fa-verify                # Path or route name of the two-factor code check
            default_target_path: /admin            # Where to redirect by default after successful authentication
            always_use_default_target_path: false  # If it should always redirect to default_target_path
            auth_code_parameter_name: _auth_code   # Name of the parameter for the two-factor authentication code
            trusted_parameter_name: _trusted       # Name of the parameter for the trusted device option
            multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)

pimcore:
    web_profiler:
        toolbar:
            excluded_routes:
                - { path: '^/admin/asset/image-editor' }
    context:
        admin:
            routes:
                - { path: ^/admin(/.*)?$ }
                - { route: ^pimcore_admin_ }

    translations:
        domains:
            - admin

flysystem:
    storages:
        pimcore.admin.storage:
            # Storage for shared admin resources, such as the user avatar, custom logos, ...
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/admin'

twig:
    globals:
        pimcore_csrf: '@Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler'
        pimcore_csp: '@Pimcore\Bundle\AdminBundle\Security\ContentSecurityPolicyHandler'

monolog:
    handlers:
        usage:
            type: stream
            path:  "%kernel.logs_dir%/usage.log"
            level: debug
            channels: ['admin_statistics']
